services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      MODEL: ${MODEL}
      PROD_DOMAIN: ${PROD_DOMAIN}
    volumes:
      - ./backend/chroma_data:/app/chroma_data  

  frontend:
    build:
      context: ./frontend
      args: 
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend
